# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.3
LABEL maintainer="dev@ballerina.io"

COPY ocr-worker.balx /home/ballerina 


CMD ballerina run --config ${CONFIG_FILE} ocr-worker.balx
