CREATE DATABASE ECOM_DB;
use ECOM_DB;

CREATE TABLE ECOM_INVENTORY (id INT AUTO_INCREMENT, description VARCHAR(1024), PRIMARY KEY(id));
CREATE TABLE ECOM_ACCOUNT (id INT AUTO_INCREMENT, name VARCHAR(1024), PRIMARY KEY(id));
CREATE TABLE ECOM_ITEM (inventory_id INT, account_id INT, quantity INT, FOREIGN KEY (inventory_id) REFERENCES ECOM_INVENTORY(id), FOREIGN KEY (account_id) REFERENCES ECOM_ACCOUNT(id), PRIMARY KEY (inventory_id, account_id));

INSERT INTO ECOM_INVENTORY (description) VALUES ("Banana");
INSERT INTO ECOM_INVENTORY (description) VALUES ("Mango");
INSERT INTO ECOM_INVENTORY (description) VALUES ("Strawberry");
INSERT INTO ECOM_INVENTORY (description) VALUES ("Water Bottle");

INSERT INTO ECOM_ACCOUNT (name) VALUES ("Jack");
INSERT INTO ECOM_ACCOUNT (name) VALUES ("Bill");



